# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Concord' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Concord
  # Required by RNFirebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

  target 'Concord-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConcordTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Concord-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Concord-tvOS

end
